### ISSUE TITLE
Iconselect does not work in IE8

### ISSUE THREAD

**Issue by tschiffler** [bug7a/iconselect.js#1]
your solution looks great, i would like to use it but there is a problem - it does not work in Internet Explorer 8

I got the messages that a method is not supported 
iconsolect.js - Row 59, Char: 13

I think that there must be a problem with the "addEventListener" that is not supported in ie8. 

After I fixed that the next problem came up with
'_View.iconSelectElement.dispatchEvent(new Event('changed'));'

Do you think its possible to enable your system to work also with ie8?

**Comment by andrepaulena** [comment]
Thanks man, you saved me

**Comment by bug7a** [comment]
>  Hi again!
>  
> I found a solution here for IE browser support.
> https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events
>  
> //_View.iconSelectElement.dispatchEvent(new Event('changed'));
> // Create the event.
> var event = document.createEvent('Event');
> event.initEvent('changed', true, true);
>  
> _View.iconSelectElement.dispatchEvent(event);
>  
> Have a great day!
>  
> /Daniel

**Comment by juanjoDiaz** [comment]
If this is fixed, it should be closed.

**Comment by RyuukiSu** [comment]
I also encountered this problem in IE11.
After testing, error is  "new Event('changed')"

Apply this method function  can solve this problem.
Ref URL:
Https://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work

```
(function () {
   If ( typeof window.CustomEvent === "function" ) return false; //If not IE

   Function CustomEvent ( event, params ) {
     Params = params || { bubbles: false, cancelable: false, detail: undefined };
     Var evt = document.createEvent( 'CustomEvent' );
     evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
     Return evt;
    }

   CustomEvent.prototype = window.Event.prototype;

   window.CustomEvent = CustomEvent;
})();
```

And this line(iconselect.js : line 116):
`_View.iconSelectElement.dispatchEvent(new Event('changed'));`

Change to:
`_View.iconSelectElement.dispatchEvent(new CustomEvent('changed'));`


--------------------
If you want to support IE11 or below, you may have to rewrite the old method fireEvent for ispatchEventf, but you may encounter outdated problems.

**Comment by bug7a** [comment]
Thanks
