### ISSUE TITLE
Doctype declaration breaks JavaScript

### ISSUE THREAD

**Issue by MartinPluta** [bug7a/iconselect.js#2]
<!Doctype html...> declarations cause the JavaScript to break. This is because of the width, height, .. attributes being assigned without the 'px' extension. This is required, if the Doctype is set to html, like so:

_View.boxScrollElement.style.height = (($parameters.iconsHeight + 2) \* $parameters.horizontalIconNumber) + (($parameters.horizontalIconNumber + 1) \* $parameters.boxIconSpace) + 'px';

This has to be applied to all of the respective elements. You will then be able to use iconselect.js, if the Doctype is declared.

Greetings Martin

**Comment by Burn-E99** [comment]
In the pull request I created, this has been fixed. You can either pull my version to fix all of this, or wait until bug7a merges this in.

**Comment by bug7a** [comment]
thank you all.

**Comment by Burn-E99** [comment]
You're welcome!  Glad we could all help make this better!

**Comment by juanjoDiaz** [comment]
If this is fixed, it should be closed.
